src/char_model_trainer.cc
src/unigram_model.cc
src/word_model_trainer.cc

I tried to compile, but I encountered a compilation error. I guess `#include <cmath>` is missing.
```
/tmp/sentencepiece # make
make  all-recursive
make[1]: Entering directory '/tmp/sentencepiece'
Making all in src
make[2]: Entering directory '/tmp/sentencepiece/src'
make  all-am
make[3]: Entering directory '/tmp/sentencepiece/src'
g++ -DHAVE_CONFIG_H -I. -I..     -std=c++11 -Wall -O3   -MT word_model_trainer.o -MD -MP -MF .deps/word_model_trai
ner.Tpo -c -o word_model_trainer.o word_model_trainer.cc
word_model_trainer.cc: In member function 'virtual void sentencepiece::word::Trainer::Train()':
word_model_trainer.cc:60:31: error: 'log' was not declared in this scope
const float logsum = log(sum);
```
I replicated the issue using alpine docker, not ubuntu.
```
FROM alpine
RUN apk add …
```

Fix missing #include <cmath>

---

src/stringpiece.h

The compiler complains that StringPiece::operator<< leads to stack
overflows due to the infinite recursion (-Winfinite-recursion).
Running the following sample program causes a stack overflow
```
$ cat stringpiece_test.cc
#include "stringpiece.h"
#include <iostream>
int main() {
std::string s("zuzuzu...");
sentencepiece::StringPiece sp(s.data(), s.size());
std::cout << sp << std::endl;
return 0;
}
$ clang++ -fsanitize=address stringpiece_test.cc
$ ./a.out
ASAN:DEADLYSIGNAL
=================================================================
==76454==ERROR: AddressSanitizer: stack-overflow on address 0x7fff59be3fa8 (pc 0x000105869745 bp 0x7fff59be4810 sp 0x7fff59be3fb0 T0)
#0 0x105869744 in wrap_strlen (libclang_rt.asan_osx_dynamic.dylib+0x45744)
#1 0x10581db81 in …
```

Fix stack-overflow in StringPiece

---

README.md
configure.ac

I am trying to build sentencepiece on iOS along with tensorflow. And I want to build sentencepiece using tensorflow's costumed protobuf. By adding a env-var checking to configure.ac, It worked. I also add some guide line to README.md on how to use self-prepared protobuf lib.

Add support to use self-prepared protobuf lib

---

src/spm_encode_main.cc

The current version of spm_encode ignores empty lines, thus the line number of its input file does not match the line number of its output file.   The filter program such as spm_encode should do its most simple work only.  If its user wants to remove empty lines, he/she can do it with `grep' command as you know.

spm_encode should not ignore empty lines

---

doc/api.md
src/sentencepiece_processor.cc
src/sentencepiece_processor.h
src/sentencepiece_processor_test.cc

Added two construction interface for SentencepieceProcessor, using std::istream to initialize the model.
These interfaces are very useful in case when we construct the model from Android assets or Network where we can only have the input stream of the model file.

std::istream interface for SentencepieceProcessor construction

---

src/sentencepiece_processor.h

"Sets **dncode** extra_option sequence." -> "Sets **decode** extra_option sequence."

Fix typo: dncode -> decode

---

python/setup.py

When `pkg-confing` command fails, the setup script shows stacktrace. I fixed it to show an error message.

Call sys.exit when pkg-config fails

---

python/setup.py

Fixed a build error by Python 3.
subprocess.check_output returns 'bytes' not 'str' in Python 3.

Fix an incompatibility problem on setup.py for Python 3.

---

src/sentencepiece.proto

There is a duplication in comments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/sentencepiece/49)

Fix typo in examples of control symbols

---

src/sentencepiece_model.proto

There is a discrepancy between actual default value `vocab_size` (8000) and its comment (32k). 
This should be fixed. I'm not sure which one is preferred, though.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/sentencepiece/48)

Fix inconsistent default vocab size

---

src/unigram_model.cc
src/unigram_model_trainer.cc

This PR removes unused variables in `unigram_model.cc` and `unigram_model_trainer.cc`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/sentencepiece/50)

Remove unused variables

---

README.md

This update resolves (or answers) #2; There is no package named `libprotobuf-c++` or `protocolbuffer`. Instead, there are different packages per each of Ubuntu distros.

Provide detailed instructions for installing the protobuf library

---

README.md

ldconfig is a linux command; update_dyld_shared_cache seems to work (courtesy of https://stackoverflow.com/a/45920815, verified on my computer).

Updating install instructions for OSX/macOS

---

src/trainer_interface.cc

when split_by_unicode_script() is true 
using clang 9.1:
```
warning: comparison of constant -1 with expression of type 'unicode_script::ScriptType' is always true [-Wtautological-constant-out-of-range-compare]
```

invalid test causing all pieces to be identified as non valid 

---

README.md

This commit fixes the syntax highlighting for the macOS' shared cache update command in the Readme.

Fixed syntax highlighting

---

README.md

Should fix #290, #221 according to code source https://github.com/google/sentencepiece/blob/master/python/sentencepiece.py#L153.

Fix Python sample typo (SampleEncodeAsPieces)

---

tensorflow/README.md

notebook link gives "Invalid Credentials" error if only one account is logged in. Works fine in incognito.

change notebook link to avoid permission errors

---

CMakeLists.txt

Some CMake version will fail during the configuration with 'Unknown extension ".c" for file' because C is not part of the language list.

Declare C language in CMakeLists.txt

---

README.md

Removes reference to that Korean has no spaces, due to that it has. [Reference](http://www.koreanwikiproject.com/wiki/Word_spacing)

Removes reference to that Korean has no spaces

---

tensorflow/tf_sentencepiece/sentencepiece_processor_ops.py

tensorflow==1.15.0
As a library file does not exists for tensorflow version 1.15.0, this command is invoked. However, the regex fails to extract the correct versions, if there are other version numbers in the full path of the library files.
**Example:**
The following path:
`"/home/<user>/<project>/.venv/lib/python3.7/site-packages/tf_sentencepiece/_sentencepiece_processor_ops.so.2.0.0"`
Gets parsed by the regex as:
`"3.7/site-packages/tf_sentencepiece/_sentencepiece_processor_ops.so.2.0.0"`
And so:
`so_file = "/home/<user>/<project>/.venv/lib/python3.7/site-packages/tf_sentencepiece/_sentencepiece_processor_ops.so.3.7/site-packages/tf_sentencepiece/_sentencepiece_processor_ops.so.2.0.0"`
Which results in:
`tensorflow.python.framework.errors_impl.NotFoundError: <path>: cannot open shared …

Fix version extraction from library files

---

tensorflow/tf_sentencepiece/sentencepiece_processor_ops.py

In the branch which is executed if no exact match is found,
extract the captured version number from the regex instead
of the complete match.
See issue #456 .

Fix library selection logic

---

CMakeLists.txt

This is useful when SentencePiece is used as a Git submodule.

Declare include directories relative to the main CMakeLists.txt

---

src/spec_parser.h

[Bugfix] Add split_digits to SentencePieceTrainer spec parser

---

CMakeLists.txt

sentencepiece.pc should be installed from CMAKE_CURRENT_BINARY_DIR, not CMAKE_BINARY_DIR, to support being included (and installed) from other projects

Install sentencepiece.pc from CMAKE_CURRENT_BINARY_DIR

---

python/sentencepiece.i
python/sentencepiece.py
src/bpe_model.h
src/sentencepiece_processor.h

Previous descriptions of alpha regarding BPE dropout are misleading.
By saying alpha to be the merge probability in BPE-dropout will make us thinking `dropout = 1 - alpha`, but it is not.
This PR fixes the descriptions across the code comments to clarify this potential misunderstanding.

clear description for alpha of BPE-dropout

---

README.md
doc/options.md

Hi,
thanks for the great package. I was missing an overview of parameters to pass to SentencePieceTrainer. When just using pip install sentencepiece, spm_train is not installed by default, and, as such, the spm_train --help command is not available. This PR adds an overview of the options (basically just an md file with the output of spm_train --help pasted in.

Add options list for training to documentation

---

README.md

The original code snipped contains underscore "_" symbol, but it should be "▁" (U+2581) instead.
This commit only fixes this typo.

Fix space symbol in code snippet: _ -> ▁

---

src/CMakeLists.txt

It requires -latomic for these platforms.

cmake: fix FTBFS on armel, mips, powerpc, m68k and sh4

---

third_party/esaxx/sais.hxx

according to the c ++ standard, the operator new cannot return a null value, but will throw an exception std :: bad_alloc (). therefore return -2 in this case will not be reachable.
the simplest thing is to remove these checks.

fix of an unattainable condition.

---

appveyor.yml

Updating the appveyor visual studio version seems to remove cpython 3.5 support and add cpython 3.9 support. Seems like you'll need to use two appveyor builds if you want to cover cpython 3.5 still.

fix appveyor python 3.9 build

---

src/util.h

util.h didn't include the necessary header file before using the `BYTE_ORDER` and `__BIG_ENDIAN` macros. On standard Linux I guess it's included indirectly, but on Android it isn't.
All undefined preprocessor macros implicitly have the value 0. So `BYTE_ORDER == __BIG_ENDIAN` became `0 == 0`, which is always true, and all Android platforms were treated as big-endian. The build still succeeded, but reading a model file crashed at runtime with the error "Trie data size exceeds the input blob size".

Add missing #include for BYTE_ORDER

---

src/builder.cc

Resolve google/sentencepiece#629
Currently, the Zero Width Joiner character has been [replaced by whitespace](https://github.com/google/sentencepiece/commit/18c337f32d376b339f15a48c7ccc5c1c288345a1#diff-c0960ff1cd2e917394da837d2a75ca10e06abab61bbd2d36f174fa284c8d700bR57266). Due to that Sinhala language that requires Zero Width Joiner getting altered and resulted in wong output. 
Ideally, we shouldn't replace Zero Width Joiner (200D) with whitespace or empty since it indicates to join two chars without zero width(no whitespace). Also, It requires to present in order to decode the segmentation to raw test successfully. We should keep these special characters as it is.
This PR eliminate the places where WZJ has replaced with whitespace. after referrog to the commit [1],
data/nmt_nfkc.tsv …

Prevent Zero Width Joiner replaced with whitespace

---

src/unigram_model_trainer.cc

This pull request suggests restoring the sentence boundary insertion code for the suffix array creation in the unigram model trainer, in order to significantly re-speedup training.
This appears to have been deleted here:
- https://github.com/google/sentencepiece/commit/329383b455a5795f3d182159eb0985a3f20f0fa2#diff-51c497698d155a53cbd00dfd1a26018599599affa606d6fd44d663d18d4535aaL116 
during the commit that 'merged the internal sentencepiece'. 
I believe this also relates to the following issues:
- https://github.com/google/sentencepiece/issues/641
- https://github.com/google/sentencepiece/issues/615
I'm not sure if there is a qualitative/modeling reason behind this change (or if there is a settings way to avoid this?), but the difference in training speed with and without this line, for …

Restore the sentence boundary marker insertion for the unigram model trainer

---

tensorflow/README.md

I've no idea why there was a random s

Fixed mistake in README

---

python/src/sentencepiece/sentencepiece.i
python/src/sentencepiece/sentencepiece_wrap.cxx

This PR fixes the following compilation error in Clang 13 on macOS.
```
❯ python setup.py build
running build
running build_py
running build_ext
-L/opt/homebrew/Cellar/sentencepiece/0.1.96/lib -lsentencepiece -lsentencepiece_train
building 'sentencepiece._sentencepiece' extension
/opt/homebrew/opt/llvm/bin/clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include -I/opt/homebrew/opt/openssl@1.1/include -I/opt/homebrew/opt/icu4c/include -I/Users/jaepil/app/include -I/opt/homebrew/include -I/opt/homebrew/opt/llvm/include -DTARGET_OS_OSX -Wno-implicit-function-declaration -Wno-availability -Wno-expansion-to-defined -Wno-nullability-completeness …
```

Fix compilation error in Clang 13 on macOS

---

python/setup.cfg

Setuptools v54.1.0 introduces a warning that the use of dash-separated options in 'setup.cfg' will not be supported in a future version [1]. Get ahead of the issue by replacing the dashes with underscores. Without this, we see 'UserWarning' messages like the following on new enough versions of setuptools:
```
UserWarning: Usage of dash-separated 'description-file' will not be
supported in future versions. Please use the underscore name
'description_file' instead
```
[1] https://github.com/pypa/setuptools/commit/a2e9ae4cb
Update setup.cfg to use underscore for 'description_file' instead of dash 'description-file' since it loses support in future versions

Update setup.cfg to use underscore for 'description_file' attribute

---

README.md
doc/experiments.md
python/sentencepiece_python_module_example.ipynb

Hi.
Fixed errors in `sentencepiece_python_module_example.ipynb` notebook:
- In 2.0, tf.gfile.* is replaced by tf.io.gfile.*: `tf.io.gfile.GFile` -> `tf**.io**.gfile.GFile`
- error during importing `sentencepiece_pb2`
- remove redundant imports
Tested in colab. "Runtime" -> "Run all" without errors.
Also fixed dead links in `README.md` and `doc/experiments.md`.

Fix example notebook

---

cmake/ios.toolchain.cmake
src/CMakeLists.txt

This PR allows to build sentencepiece for iOS platforms. To do so just do:
```
mkdir build
cd build 
cmake .. -G Xcode -DCMAKE_TOOLCHAIN_FILE=../cmake/ios.toolchain.cmake -DPLATFORM=OS64
cmake --build . --config Release
```

Enable iOS builds

---

.github/workflows/cifuzz.yml

Add [CIFuzz](https://google.github.io/oss-fuzz/getting-started/continuous-integration/) workflow action to have fuzzers build and run on each PR.
This is a service offered by OSS-Fuzz where sentencepiece already runs. CIFuzz can help detect regressions and catch fuzzing build issues early, and has a variety of features (see the URL above). In the current PR the fuzzers gets build on a pull request and will run for 300 seconds.
Signed-off-by: David Korczynski <david@adalogics.com>

add CIFuzz GitHub action

---

CMakeLists.txt

I'm sorry 🙏  but I thought cmake accepted without the `endif` clause.

CMake need endif

---

python/add_new_vocab.ipynb

Hello.
I have noticed that a tutorial that is committed is not working.
This is because the path has changed since this tutorial was [committed](https://github.com/google/sentencepiece/tree/c091f894a8f767e0b15d20720668943a58ab1313/python).
So I want to fix this tutorial.

fix the path in add_new_vocab.ipynb

---

.github/workflows/cmake.yml
.github/workflows/wheel.yml

Fixes this error:
Build wheels on ubuntu-latest
Unable to resolve action `actions/setup-python@v4.5`, unable to find version `v4.5`
https://github.com/google/sentencepiece/actions/runs/4204923860

Fix setup-python version not detected

---

CMakeLists.txt

See details in the ticket https://github.com/google/sentencepiece/issues/825#event-8773663277
Since MSVC 2015 the MSVC runtime is compatible. So, we don't have to force users to compile their applications and libraries with static MSVC runtime, while default MSVC behavior is /MD
If someone still needs static runtime, he / she is suggested to use cmake's option designed for this purpose [CMAKE_MSVC_RUNTIME_LIBRARY](https://cmake.org/cmake/help/latest/variable/CMAKE_MSVC_RUNTIME_LIBRARY.html)
Example:
```cmake
cmake -D CMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded 
```

Removed replacing of /MD with /MT for MSVC

---

CMakeLists.txt
sentencepiece.pc.in

This PR fixes the pkg-config file so that it does not suggest linking with libprotobuf-lite (when sentencepiece has been configured for external protobuf using `-DSPM_USE_BUILTIN_PROTOBUF=OFF`) unless static linking is requested.
While I was there, I also removed some unused placeholders.
```sh
% pkg-config sentencepiece --libs
-L/opt/local/lib -lsentencepiece -lsentencepiece_train -lprotobuf-lite
% pkg-config sentencepiece --libs --static
-L/opt/local/lib -lsentencepiece -lsentencepiece_train -lprotobuf-lite
```
```sh
% pkg-config sentencepiece --libs
-L/opt/local/lib -lsentencepiece -lsentencepiece_train
% pkg-config sentencepiece --libs --static
-L/opt/local/lib -lsentencepiece -lsentencepiece_train -lprotobuf-lite
```

Fix overlinking with protobuf

---

.github/dependabot.yml
.github/workflows/cifuzz.yml
.github/workflows/cmake.yml
.github/workflows/cross_build.yml
.github/workflows/wheel.yml

Fixes #.
As described in the issue, this PR hash-pins the GitHub Actions used in the workflows to protect the project from supply-chain attacks.
The only exception are the oss-fuzz Actions which unfortunately require running `@master` to work properly.
This PR also adds Dependabot to keep the Actions up-to-date. It is configured to send at most one PR a month updating all Actions with new versions.

Hash-pin GitHub Actions, add dependabot

---

.github/workflows/cifuzz.yml
.github/workflows/cmake.yml
.github/workflows/cross_build.yml
.github/workflows/wheel.yml

Fixes #937.
This PR sets read-only top-level permissions on all SentencePiece workflows. The jobs that add artifacts to releases (in `cmake.yml` and `wheel.yml`) are granted additional permissions at the job level for future-proofing in case new jobs are ever added to the workflow.

Set minimal permissions for GitHub workflows

---

src/spm_encode_main.cc

`sample_(piece|id|proto)` was listed in the github README but not in the actual flag docs, and so it was hard to know how to do subword regularization from the command line.

Add missing output formats to spm_encode flag documentation

---

src/normalizer.cc

1x fixed typo
1x Changed uint32 to uint32_t for consistency and type safety. 1x The original code uses const_cast<char*> before reinterpreting it as uint32*. Without const_cast, the compiler will treat the blob.data() as a pointer to constant data (since std::string is typically constant).

Fixing issues with the normalizer.cc (typo, type safety, cast fucn)

---

python/sentencepiece_python_module_example.ipynb

Consistency of --vocab_size=2000 for sentence piece trainer. Fixing various spelling mistakes

adding vocab_size consistency

---

CMakeLists.txt

fixes future deprecation
```
CMake Deprecation Warning at lib/sentencepiece/CMakeLists.txt:15 (cmake_minimum_required):
Compatibility with CMake < 3.5 will be removed from a future version of
CMake.
Update the VERSION argument <min> value or use a ...<max> suffix to tell
CMake that the project does not need compatibility with older versions.
```

bump CMake minimum required version to avoid warnings

---

.github/workflows/wheel.yml
python/README.md
python/setup.py

Recently, I attempted to install sentencepiece using pip on Windows on ARM, but due to `python/setup.py` not taking into account `arm64` in the judgment of Windows arch, cmake mistakenly built the lib for the `AMD64` architecture. 
https://github.com/google/sentencepiece/blob/2de10cb30e982b980125d4713236dd2b29cc5f0c/python/setup.py#L125-L137
I added a judgment for `arm64` through `platform.machine()`, without modifying the judgment statements for x86 and x64, to ensure that it does not have any side effects on the original architecture building.
At the same time, I have added a section in the Python build documentation that explains how to build from source code on Windows for the convenience of Windows users.
I've also modified the `.github/workflows/wheel.yml` to build wheels for …

Add support for windows arm64

---

python/setup.py
src/common.h

This PR contains two fixes for issues found during porting on AIX OS.
-  Fix for below error to handle the processing of  endian.h . This file is not available in AIX.
```
In file included from /sentencepiece/src/pretokenizer_for_training.h:21,
from /sentencepiece/src/pretokenizer_for_training.cc:14:
/sentencepiece/src/common.h:70:10: fatal error: endian.h: No such file or directory
70 | #include <endian.h>
|          ^~~~~~~~~~
compilation terminated.
```
- Fix for below AIX linker error while doing python binding installation .
```
ld: 0706-012 The -t flag is not recognized.
ld: 0706-027 The -i flag is ignored.
ld: 0706-012 The -p flag is not recognized.
ld: 0706-012 The -- flag is not recognized.
ld: 0706-012 The -a flag is not recognized.
```

AIX porting changes

---

.github/workflows/requirements/cibuildwheel.txt

Updates `cibuildwheel` to v2.20.0, the first version that enables py3.13 builds by default.
It may be preferred to target [v2.21.3](https://github.com/pypa/cibuildwheel/releases/tag/v2.21.3) (uses `py3.13.0` instead of `py3.13.0rc1`), or [v2.22.0](https://github.com/pypa/cibuildwheel/releases/tag/v2.22.0) (current latest), though >=[v2.21.0](https://github.com/pypa/cibuildwheel/releases/tag/v2.21.0) would alter some supported macOS versions.
This would also be resolved by #1080.
Combined with #1085, this should resolve #1069, #1076, and #1083.

Upgrade cibuildwheel to v2.20.0 (build for python3.13)

---

src/unigram_model_trainer.cc

This commit cherry-picks a previous bug fix in 0fe7add.
This change was blasted away in a rebase conflict in 53de765.

fix crash in unigram model training

---

src/sentencepiece_processor.h

Fixes "`uint32_t` does not name a type" gemma.cpp build errors

Add missing <cstdint> in sentencepiece_processor.h

---

.github/workflows/wheel.yml
python/.gitignore
python/test/sentencepiece_test.py

Run the whole test suite with pytest-run-parallel.
- The new tests prove that the pattern
```python
spm.SentencePieceTrainer.train(...)
sp = spm.SentencePieceProcessor()
sp.Load(...)
```
is thread safe as long as multiple calls don't share the same objects; and that 
- everything else - e.g. `SentencePieceProcessor.Normalize()` - is safe even while sharing the same `SentencePieceProcessor` object (this is because pytest-run-parallel does not parallelise `setUp`, so all threads use the same shared state).
Notable exclusion is the `logstream=` parameter, which is NOT thread safe. However it is undocumented and untested, which makes it fall out of scope of this PR.
Note how the stress testing performed by pytest-run-parallel is stochastic, and that on 4 threads it is unlikely to catch the …

Free-threading tests

---

CMakeLists.txt

[CMake 4.0 removed compatibility with 3.5 and earlier versions.](https://cmake.org/cmake/help/latest/release/4.0.html#deprecated-and-removed-features)

Bump cmake_minimum_required to satisfy CMake 4.0

---

.github/workflows/wheel.yml

This PR adds supports for macOS between 10.13 and 11.
Locally tested to be working on macOS 10.13. No longer show any error on `import sentencepiece`.
Closes #1099.

Add support for macOS >= 10.13
